import * as generalCommands from './general';
import * as nationCommands from './nation';

export const CommandRegistry: Record<string, any> = {
  '휴식': generalCommands.RestCommand,
  '단련': generalCommands.TrainCommand,
  '치료': generalCommands.HealCommand,
  '모집': generalCommands.RecruitCommand,
  '징병': generalCommands.ConscriptCommand,
  '이동': generalCommands.MoveCommand,
  '귀환': generalCommands.ReturnCommand,
  '접경귀환': generalCommands.BorderReturnCommand,
  '농업': generalCommands.CultivateFarmCommand,
  '상업': generalCommands.InvestCommerceCommand,
  '기술연구': generalCommands.ResearchTechCommand,
  '방어': generalCommands.ReinforceDefenseCommand,
  '치안': generalCommands.ReinforceSecurityCommand,
  '성벽': generalCommands.RepairWallCommand,
  '집중훈련': generalCommands.IntensiveTrainingCommand,
  '부대훈련': generalCommands.TrainTroopsCommand,
  '사기': generalCommands.BoostMoraleCommand,
  '출병': generalCommands.DeployCommand,
  '건국': generalCommands.FoundNationCommand,
  '무작위건국': generalCommands.RandomFoundNationCommand,
  '하야': generalCommands.AbdicateCommand,
  '은퇴': generalCommands.RetireCommand,
  '인재등용': generalCommands.SearchTalentCommand,
  '해산': generalCommands.DisbandCommand,
  '견문': generalCommands.SightseeingCommand,
  '군량매매': generalCommands.TradeRiceCommand,
  '농지개간': generalCommands.CultivateLandCommand,
  '선양': generalCommands.AbdicateToCommand,
  'NPC능동': generalCommands.NpcAutoCommand,
  '방랑': generalCommands.WanderCommand,
  '순행': generalCommands.TravelCommand,
  '모병': generalCommands.RecruitSoldiersCommand,
  '물자조달': generalCommands.ProcureSupplyCommand,
  '전투태세': generalCommands.BattleStanceCommand,
  '전투특기초기화': generalCommands.ResetBattleSkillCommand,
  '내정특기초기화': generalCommands.ResetAdminSkillCommand,
  '정착장려': generalCommands.EncourageSettlementCommand,
  '주민선정': generalCommands.SelectCitizenCommand,
  '증여': generalCommands.GrantCommand,
  '헌납': generalCommands.DonateCommand,
  '탈취': generalCommands.PlunderCommand,
  '파괴': generalCommands.DestroyCommand,
  '화계': generalCommands.FireAttackCommand,
  '강행': generalCommands.ForceMarchCommand,
  '집합': generalCommands.GatherCommand,
  '거병': generalCommands.RaiseArmyCommand,
  '첩보': generalCommands.SpyCommand,
  '등용': generalCommands.RecruitGeneralCommand,
  '등용수락': generalCommands.AcceptRecruitCommand,
  '임관': generalCommands.JoinNationCommand,
  '랜덤임관': generalCommands.RandomJoinNationCommand,
  '모반시도': generalCommands.AttemptRebellionCommand,
  '선동': generalCommands.AgitateCommand,
  '장비매매': generalCommands.TradeEquipmentCommand,
  '군사매매': generalCommands.TradeMilitaryCommand,
  '숙련전환': generalCommands.ConvertExpCommand,
  '요양': generalCommands.RestCureCommand,
  '성벽보수': generalCommands.RepairWallExtendCommand,
  '소집해제': generalCommands.DismissTroopsCommand,
  '수비강화': generalCommands.ReinforceDefenseExtendCommand,
  '장수대상임관': generalCommands.JoinGeneralNationCommand,
};

export const NationCommandRegistry: Record<string, any> = {
  '감축': nationCommands.ReduceForceCommand,
  '국기변경': nationCommands.che_국기변경,
  '국호변경': nationCommands.che_국호변경,
  '급습': nationCommands.RaidCommand,
  '피장파장': nationCommands.CounterAttackCommand,
  '몰수': nationCommands.che_몰수,
  '무작위수도이전': nationCommands.RandomCapitalMoveCommand,
  '물자원조': nationCommands.che_물자원조,
  '발령': nationCommands.AppointOfficerCommand,
  '백성동원': nationCommands.che_백성동원,
  '부대탈퇴지시': nationCommands.che_부대탈퇴지시,
  '불가침수락': nationCommands.che_불가침수락,
  '불가침제의': nationCommands.che_불가침제의,
  '불가침파기수락': nationCommands.che_불가침파기수락,
  '불가침파기제의': nationCommands.che_불가침파기제의,
  '선전포고': nationCommands.DeclareWarCommand,
  '수몰': nationCommands.che_수몰,
  '의병모집': nationCommands.che_의병모집,
  '이호경식': nationCommands.che_이호경식,
  '종전수락': nationCommands.che_종전수락,
  '종전제의': nationCommands.che_종전제의,
  '증축': nationCommands.ExpandCommand,
  '천도': nationCommands.MoveCapitalCommand,
  '초토화': nationCommands.che_초토화,
  '포상': nationCommands.RewardCommand,
  '필사즉생': nationCommands.che_필사즉생,
  '허보': nationCommands.che_허보,
  '인구이동': nationCommands.CrPopulationMoveCommand,
  '극병연구': nationCommands.event_극병연구,
  '대검병연구': nationCommands.event_대검병연구,
  '무희연구': nationCommands.event_무희연구,
  '산저병연구': nationCommands.event_산저병연구,
  '상병연구': nationCommands.event_상병연구,
  '원융노병연구': nationCommands.event_원융노병연구,
  '음귀병연구': nationCommands.event_음귀병연구,
  '화륜차연구': nationCommands.event_화륜차연구,
  '화시병연구': nationCommands.event_화시병연구,
  '휴식': nationCommands.RestCommand,
};

export function getCommand(action: string) {
  return CommandRegistry[action] || null;
}

export function getNationCommand(action: string) {
  return NationCommandRegistry[action] || null;
}

export * from './base/BaseCommand';
export * from './base/GeneralCommand';
export * from './base/NationCommand';
