/**
 * GIN7 Scenario Events Index
 *
 * 모든 시나리오 이벤트 데이터 통합 export
 */

// Imperial Events
export {
  IMPERIAL_EVENT_IDS,
  IMPERIAL_EVENTS,
  LIPSTADT_WAR_START_EVENT,
  NOBLE_ALLIANCE_FORMATION_EVENT,
  WESTERLAND_MASSACRE_EVENT,
  GEIERSBURG_BATTLE_EVENT,
  getImperialEventById,
  getImperialEventsByTrigger,
} from './imperial_events';

// Alliance Events
export {
  ALLIANCE_EVENT_IDS,
  ALLIANCE_EVENTS,
  MILITARY_CONGRESS_COUP_EVENT,
  YANG_WENLI_RETURN_EVENT,
  VERMILION_BATTLE_EVENT,
  CEASEFIRE_ORDER_EVENT,
  getAllianceEventById,
  getAllianceEventsByTrigger,
} from './alliance_events';

// Independence Events
export {
  INDEPENDENCE_EVENT_IDS,
  INDEPENDENCE_EVENTS,
  EL_FACIL_INDEPENDENCE_EVENT,
  EL_FACIL_REVOLUTION_EVENT,
  AUTONOMY_CHANGE_EVENT,
  ISERLOHN_REPUBLIC_EVENT,
  PHEZZAN_NEUTRALITY_END_EVENT,
  getIndependenceEventById,
  getIndependenceEventsByTrigger,
} from './independence_events';

// Re-export defaults
import IMPERIAL_EVENTS from './imperial_events';
import ALLIANCE_EVENTS from './alliance_events';
import INDEPENDENCE_EVENTS from './independence_events';

/**
 * 모든 시나리오 이벤트 통합 배열
 */
export const ALL_SCENARIO_EVENTS = [
  ...IMPERIAL_EVENTS,
  ...ALLIANCE_EVENTS,
  ...INDEPENDENCE_EVENTS,
];

/**
 * 진영별 이벤트 ID 상수 통합
 */
export const ALL_EVENT_IDS = {
  IMPERIAL: {
    LIPSTADT_WAR_START: 'EVT_IMP_LIPSTADT_START',
    NOBLE_ALLIANCE_FORMATION: 'EVT_IMP_NOBLE_ALLIANCE',
    WESTERLAND_MASSACRE: 'EVT_IMP_WESTERLAND',
    GEIERSBURG_BATTLE: 'EVT_IMP_GEIERSBURG',
    REINHARD_CORONATION: 'EVT_IMP_REINHARD_CORONATION',
    LICHTENLADE_REMOVAL: 'EVT_IMP_LICHTENLADE_REMOVAL',
    BRAUNSCHWEIG_DEATH: 'EVT_IMP_BRAUNSCHWEIG_DEATH',
    LITTENHEIM_DEATH: 'EVT_IMP_LITTENHEIM_DEATH',
  },
  ALLIANCE: {
    MILITARY_CONGRESS_COUP: 'EVT_ALL_MILITARY_COUP',
    GREENHILL_ARREST: 'EVT_ALL_GREENHILL_ARREST',
    ARTEMIS_NECKLACE_BATTLE: 'EVT_ALL_ARTEMIS_BATTLE',
    YANG_WENLI_RETURN: 'EVT_ALL_YANG_RETURN',
    YANG_INQUIRY_HEARING: 'EVT_ALL_YANG_INQUIRY',
    VERMILION_BATTLE: 'EVT_ALL_VERMILION',
    CEASEFIRE_ORDER: 'EVT_ALL_CEASEFIRE',
    TRUNICHT_ESCAPE: 'EVT_ALL_TRUNICHT_ESCAPE',
    BUCOCK_LAST_STAND: 'EVT_ALL_BUCOCK_STAND',
  },
  INDEPENDENCE: {
    EL_FACIL_INDEPENDENCE: 'EVT_IND_EL_FACIL',
    EL_FACIL_REVOLUTION: 'EVT_IND_EL_FACIL_REV',
    EL_FACIL_JOIN_YANG: 'EVT_IND_EL_FACIL_YANG',
    AUTONOMY_CHANGE: 'EVT_IND_AUTONOMY',
    AUTONOMY_EXPANSION: 'EVT_IND_AUTONOMY_EXPAND',
    AUTONOMY_RESTRICTION: 'EVT_IND_AUTONOMY_RESTRICT',
    ISERLOHN_REPUBLIC: 'EVT_IND_ISERLOHN_REPUBLIC',
    PHEZZAN_NEUTRALITY_END: 'EVT_IND_PHEZZAN_NEUTRAL_END',
  },
} as const;

export default ALL_SCENARIO_EVENTS;







